//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bandwidth
    {
        public int bandwidthid { get; set; }
        public Nullable<int> networkid { get; set; }
        public string gd { get; set; }
        public Nullable<short> portsocketmode { get; set; }
        public string tps { get; set; }
        public string tpsport { get; set; }
        public Nullable<short> frequencyindex { get; set; }
        public Nullable<System.DateTime> timestamp_lastyear { get; set; }
        public Nullable<double> lastyear { get; set; }
        public Nullable<System.DateTime> timestamp_lastmonth { get; set; }
        public Nullable<double> lastmonth { get; set; }
        public Nullable<System.DateTime> timestamp_lastweek { get; set; }
        public Nullable<double> lastweek { get; set; }
        public Nullable<System.DateTime> timestamp_lastday { get; set; }
        public Nullable<double> lastday { get; set; }
        public Nullable<System.DateTime> timestamp_lasthour { get; set; }
        public Nullable<double> lasthour { get; set; }
        public Nullable<byte> active { get; set; }
    }
}
