//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuLieuTron
    {
        public int DuLieuTronID { get; set; }
        public Nullable<int> HopDongID { get; set; }
        public string MaHopDong { get; set; }
        public string TenHopDong { get; set; }
        public Nullable<System.DateTime> NgayHopDong { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> CongTruongID { get; set; }
        public Nullable<int> MACID { get; set; }
        public string DoSut { get; set; }
        public Nullable<decimal> KLDatHang { get; set; }
        public Nullable<decimal> KLDaGiao { get; set; }
        public Nullable<decimal> KLConLai { get; set; }
        public Nullable<decimal> KLTaoPhieuTron { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> LastStatus { get; set; }
        public int LnNo { get; set; }
        public string NPKhachHangMaKhachHang { get; set; }
        public string NPKhachHangTenKhachHang { get; set; }
        public string NPCongTruongMaCongTruong { get; set; }
        public string NPCongTruongTenCongTruong { get; set; }
        public string NPMACMaMAC { get; set; }
        public string NPMACTenMAC { get; set; }
        public Nullable<decimal> DLT_KLDuTinh { get; set; }
        public Nullable<decimal> DLT_KLTronNhoNhat { get; set; }
        public Nullable<decimal> DLT_KLTronLonNhat { get; set; }
        public Nullable<decimal> DLT_KLDuTinhCuaTungMe { get; set; }
        public Nullable<decimal> DLT_KLDuTinhCuaTungMe_NoiB { get; set; }
        public bool DLT_KLDuTinhCuaTungMe_NoiB_IsUsed { get; set; }
        public Nullable<decimal> DLT_KLBuTruMeCuoi { get; set; }
        public Nullable<decimal> DLT_SLMeDuTinh { get; set; }
        public Nullable<decimal> DLT_KLXeChoLonNhat { get; set; }
        public Nullable<decimal> DLT_MACSUMSiloValueCalc { get; set; }
        public Nullable<decimal> DLT_MACSUMSiloValue { get; set; }
        public bool Activated { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
        public byte[] VersionNo { get; set; }
        public Nullable<int> HangMucID { get; set; }
    
        public virtual HopDong HopDong { get; set; }
    }
}
