//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int EventLogID { get; set; }
        public string LogCode { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public int EventActionCodeID { get; set; }
        public string EventActionContent { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> OldValueNumeric { get; set; }
        public Nullable<decimal> NewValueNumeric { get; set; }
        public string OldValueText { get; set; }
        public string NewValueText { get; set; }
        public string Title1 { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public string Content1 { get; set; }
        public string Title2 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public string Content2 { get; set; }
        public string Title3 { get; set; }
        public Nullable<decimal> Value3 { get; set; }
        public string Content3 { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
        public byte[] VersionNo { get; set; }
    
        public virtual EventActionCode EventActionCode { get; set; }
    }
}
