//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.DuLieuTrons = new HashSet<DuLieuTron>();
            this.PhieuTrons = new HashSet<PhieuTron>();
        }
    
        public int HopDongID { get; set; }
        public string MaHopDong { get; set; }
        public string TenHopDong { get; set; }
        public Nullable<System.DateTime> NgayHopDong { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> CongTruongID { get; set; }
        public Nullable<int> MACID { get; set; }
        public string DoSut { get; set; }
        public Nullable<decimal> KLDatHang { get; set; }
        public Nullable<decimal> KLDaGiao { get; set; }
        public Nullable<decimal> KLConLai { get; set; }
        public Nullable<decimal> KLTaoPhieuTron { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> DLT_KLDuTinh { get; set; }
        public Nullable<decimal> DLT_KLTronNhoNhat { get; set; }
        public Nullable<decimal> DLT_KLTronLonNhat { get; set; }
        public Nullable<decimal> DLT_KLDuTinhCuaTungMe { get; set; }
        public Nullable<decimal> DLT_KLDuTinhCuaTungMe_NoiB { get; set; }
        public bool DLT_KLDuTinhCuaTungMe_NoiB_IsUsed { get; set; }
        public Nullable<decimal> DLT_KLBuTruMeCuoi { get; set; }
        public Nullable<decimal> DLT_SLMeDuTinh { get; set; }
        public Nullable<decimal> DLT_KLXeChoLonNhat { get; set; }
        public Nullable<decimal> DLT_MACSUMSiloValueCalc { get; set; }
        public Nullable<decimal> DLT_MACSUMSiloValue { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
        public byte[] VersionNo { get; set; }
        public Nullable<int> HangMucID { get; set; }
        public Nullable<int> TongPhieu { get; set; }
    
        public virtual CongTruong CongTruong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuLieuTron> DuLieuTrons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual MAC MAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuTron> PhieuTrons { get; set; }
        public virtual HangMuc HangMuc { get; set; }
    }
}
