//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACSilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MACSilo()
        {
            this.MeTronChiTiets = new HashSet<MeTronChiTiet>();
            this.MeTronChiTietGiaoHangs = new HashSet<MeTronChiTietGiaoHang>();
        }
    
        public int MACSiloID { get; set; }
        public int MACID { get; set; }
        public int SiloID { get; set; }
        public Nullable<decimal> SiloValue { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
    
        public virtual MAC MAC { get; set; }
        public virtual Silo Silo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeTronChiTiet> MeTronChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeTronChiTietGiaoHang> MeTronChiTietGiaoHangs { get; set; }
    }
}
