//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeTron
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeTron()
        {
            this.MeTronChiTiets = new HashSet<MeTronChiTiet>();
            this.MeTronChiTietGiaoHangs = new HashSet<MeTronChiTietGiaoHang>();
        }
    
        public int MeTronID { get; set; }
        public Nullable<int> LnNo { get; set; }
        public Nullable<System.DateTime> NgayMeTron { get; set; }
        public int PhieuTronID { get; set; }
        public Nullable<decimal> KhoiLuong { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
    
        public virtual PhieuTron PhieuTron { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeTronChiTiet> MeTronChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeTronChiTietGiaoHang> MeTronChiTietGiaoHangs { get; set; }
    }
}
