//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuGiaoHang
    {
        public int PhieuTronID { get; set; }
        public string MaPhieuTron { get; set; }
        public Nullable<System.DateTime> NgayPhieuTron { get; set; }
        public Nullable<decimal> KLDuTinh { get; set; }
        public Nullable<decimal> KLThuc { get; set; }
        public Nullable<decimal> KLTronNhoNhat { get; set; }
        public Nullable<decimal> KLTronLonNhat { get; set; }
        public Nullable<decimal> KLDuTinhCuaTungMe { get; set; }
        public Nullable<decimal> KLBuTruMeCuoi { get; set; }
        public Nullable<decimal> SLMeDuTinh { get; set; }
        public Nullable<decimal> SLMeHieuChinh { get; set; }
        public Nullable<decimal> SLMeDaTron { get; set; }
        public Nullable<int> HopDongID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public string TenKhachHang { get; set; }
        public Nullable<int> CongTruongID { get; set; }
        public string TenCongTruong { get; set; }
        public Nullable<int> HangMucID { get; set; }
        public string TenHangMuc { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<int> MACID { get; set; }
        public string TenMAC { get; set; }
        public string CuongDo { get; set; }
        public string DoSut { get; set; }
        public Nullable<decimal> TheTich { get; set; }
        public Nullable<decimal> LuyKe { get; set; }
        public Nullable<int> TaiXeID { get; set; }
        public string TenTaiXe { get; set; }
        public Nullable<int> XeID { get; set; }
        public string BienSo { get; set; }
        public string NiemChi { get; set; }
        public string NguoiTron { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
        public string MaHopDong { get; set; }
        public Nullable<int> NoPhieu { get; set; }
        public string GioKT { get; set; }
        public string GioBD { get; set; }
    }
}
