//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTron
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuTron()
        {
            this.MeTrons = new HashSet<MeTron>();
        }
    
        public int PhieuTronID { get; set; }
        public string MaPhieuTron { get; set; }
        public Nullable<System.DateTime> NgayPhieuTron { get; set; }
        public Nullable<decimal> KLDuTinh { get; set; }
        public Nullable<decimal> KLThuc { get; set; }
        public Nullable<decimal> KLTronNhoNhat { get; set; }
        public Nullable<decimal> KLTronLonNhat { get; set; }
        public Nullable<decimal> KLDuTinhCuaTungMe { get; set; }
        public Nullable<decimal> KLBuTruMeCuoi { get; set; }
        public Nullable<decimal> SLMeDuTinh { get; set; }
        public Nullable<decimal> SLMeHieuChinh { get; set; }
        public Nullable<decimal> SLMeDaTron { get; set; }
        public Nullable<int> HopDongID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> CongTruongID { get; set; }
        public Nullable<int> MACID { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> NguoiTron { get; set; }
        public Nullable<System.DateTime> ThoiGianTron { get; set; }
        public Nullable<bool> IsQueued { get; set; }
        public Nullable<decimal> MinKLTron { get; set; }
        public Nullable<decimal> MaxKLTron { get; set; }
        public Nullable<decimal> MaxKLXeCho { get; set; }
        public Nullable<int> XeID { get; set; }
        public Nullable<int> TaiXeID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> HangMucID { get; set; }
        public Nullable<int> NoPhieu { get; set; }
    
        public virtual CongTruong CongTruong { get; set; }
        public virtual HopDong HopDong { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual MAC MAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeTron> MeTrons { get; set; }
        public virtual TaiXe TaiXe { get; set; }
        public virtual Xe Xe { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual HangMuc HangMuc { get; set; }
    }
}
