//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptTongTungXe
    {
        public int MeTronID { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> Phieu { get; set; }
        public Nullable<int> PhieuTronID { get; set; }
        public string MaPhieuTron { get; set; }
        public Nullable<int> HD { get; set; }
        public string NoteHD { get; set; }
        public string MaHopDong { get; set; }
        public string KH { get; set; }
        public string NoteKH { get; set; }
        public string CT { get; set; }
        public string NoteCT { get; set; }
        public Nullable<int> TaiXeID { get; set; }
        public string Name { get; set; }
        public string TX { get; set; }
        public Nullable<int> TX_int { get; set; }
        public string Plate { get; set; }
        public string MAC { get; set; }
        public string NoteMAC { get; set; }
        public string DoSut { get; set; }
        public Nullable<int> KLVC { get; set; }
        public Nullable<decimal> KLMe { get; set; }
        public Nullable<decimal> Agg1 { get; set; }
        public Nullable<decimal> Agg2 { get; set; }
        public Nullable<decimal> Agg3 { get; set; }
        public Nullable<decimal> Agg4 { get; set; }
        public Nullable<decimal> Agg5 { get; set; }
        public Nullable<decimal> Ce1 { get; set; }
        public Nullable<decimal> Ce2 { get; set; }
        public Nullable<decimal> Ce3 { get; set; }
        public Nullable<decimal> Ce4 { get; set; }
        public Nullable<decimal> Ce5 { get; set; }
        public Nullable<decimal> Ce6 { get; set; }
        public Nullable<decimal> Wa1 { get; set; }
        public Nullable<decimal> Wa2 { get; set; }
        public Nullable<decimal> Add1 { get; set; }
        public Nullable<decimal> Add2 { get; set; }
        public Nullable<decimal> Add3 { get; set; }
        public Nullable<decimal> Add4 { get; set; }
        public Nullable<decimal> Add5 { get; set; }
        public Nullable<decimal> Add6 { get; set; }
        public Nullable<decimal> Add7 { get; set; }
        public Nullable<decimal> Add8 { get; set; }
        public Nullable<decimal> Agg1_Bat { get; set; }
        public Nullable<decimal> Agg2_Bat { get; set; }
        public Nullable<decimal> Agg3_Bat { get; set; }
        public Nullable<decimal> Agg4_Bat { get; set; }
        public Nullable<decimal> Agg5_Bat { get; set; }
        public Nullable<decimal> Ce1_Bat { get; set; }
        public Nullable<decimal> Ce2_Bat { get; set; }
        public Nullable<decimal> Ce3_Bat { get; set; }
        public Nullable<decimal> Ce4_Bat { get; set; }
        public Nullable<decimal> Ce5_Bat { get; set; }
        public Nullable<decimal> Ce6_Bat { get; set; }
        public Nullable<decimal> Wa1_Bat { get; set; }
        public Nullable<decimal> Wa2_Bat { get; set; }
        public Nullable<decimal> Add1_Bat { get; set; }
        public Nullable<decimal> Add2_Bat { get; set; }
        public Nullable<decimal> Add3_Bat { get; set; }
        public Nullable<decimal> Add4_Bat { get; set; }
        public Nullable<decimal> Add5_Bat { get; set; }
        public Nullable<decimal> Add6_Bat { get; set; }
        public Nullable<decimal> Add7_Bat { get; set; }
        public Nullable<decimal> Add8_Bat { get; set; }
        public Nullable<decimal> TKLVC { get; set; }
    }
}
