//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_Assembly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEC_Assembly()
        {
            this.SEC_TypeInfo = new HashSet<SEC_TypeInfo>();
        }
    
        public int AssemblyID { get; set; }
        public string AssemblyInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_TypeInfo> SEC_TypeInfo { get; set; }
    }
}
