//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_Function
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEC_Function()
        {
            this.SEC_RoleFunction = new HashSet<SEC_RoleFunction>();
        }
    
        public int FunctionID { get; set; }
        public string FunctionCode { get; set; }
        public string FunctionName { get; set; }
        public string MenuName { get; set; }
        public string OtherName { get; set; }
        public Nullable<int> FunctionType { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsStatic { get; set; }
        public Nullable<bool> ShowAsBarItem { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> BeginAsAGroup { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Description { get; set; }
        public Nullable<int> TypeInfoID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
    
        public virtual SEC_TypeInfo SEC_TypeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_RoleFunction> SEC_RoleFunction { get; set; }
    }
}
