//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_TypeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEC_TypeInfo()
        {
            this.SEC_Function = new HashSet<SEC_Function>();
        }
    
        public int TypeInfoID { get; set; }
        public string TypeInfo { get; set; }
        public Nullable<int> AssemblyID { get; set; }
    
        public virtual SEC_Assembly SEC_Assembly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_Function> SEC_Function { get; set; }
    }
}
