//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Silo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Silo()
        {
            this.MACSiloes = new HashSet<MACSilo>();
            this.Silo1 = new HashSet<Silo>();
            this.NhapKhoes = new HashSet<NhapKho>();
            this.TonKhoes = new HashSet<TonKho>();
            this.XuatKhoes = new HashSet<XuatKho>();
        }
    
        public int SiloID { get; set; }
        public string MaSilo { get; set; }
        public string TenSilo { get; set; }
        public int NhomSiloID { get; set; }
        public Nullable<int> SoTT { get; set; }
        public Nullable<decimal> SaiSoDuoi { get; set; }
        public Nullable<decimal> SaiSoTren { get; set; }
        public Nullable<decimal> KLCanNhoNhat { get; set; }
        public Nullable<decimal> KLCanLonNhat { get; set; }
        public Nullable<decimal> TGNhapNhaOn { get; set; }
        public Nullable<decimal> TGNhapNhaOff { get; set; }
        public Nullable<decimal> TGKiemTraVatLieuRoi { get; set; }
        public Nullable<decimal> KLRoi { get; set; }
        public Nullable<decimal> K_Pulse { get; set; }
        public Nullable<decimal> KLDT_Tu1 { get; set; }
        public Nullable<decimal> KLDT_Tu2 { get; set; }
        public Nullable<decimal> KLDT_Tu3 { get; set; }
        public Nullable<decimal> KLDT_Den1 { get; set; }
        public Nullable<decimal> KLDT_Den2 { get; set; }
        public Nullable<decimal> KLDT_Den3 { get; set; }
        public Nullable<decimal> KLDT_DungTruoc1 { get; set; }
        public Nullable<decimal> KLDT_DungTruoc2 { get; set; }
        public Nullable<decimal> KLDT_DungTruoc3 { get; set; }
        public Nullable<int> TinhDoHutNuocID { get; set; }
        public string TinhDoHutNuocName { get; set; }
        public Nullable<decimal> DoAm_NhomSlioAgg { get; set; }
        public Nullable<decimal> DoHutNuoc_NhomSiloAgg { get; set; }
        public Nullable<decimal> SoiTrongCat_NhomSiloAgg { get; set; }
        public Nullable<int> SoiTrongCat_TruVaoSilo_NhomSiloAgg { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
        public byte[] VersionNo { get; set; }
        public Nullable<bool> BuTruKLMT { get; set; }
        public Nullable<bool> TuDongXNCD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MACSilo> MACSiloes { get; set; }
        public virtual Material Material { get; set; }
        public virtual NhomSilo NhomSilo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Silo> Silo1 { get; set; }
        public virtual Silo Silo2 { get; set; }
        public virtual TinhDoHutNuoc TinhDoHutNuoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapKho> NhapKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TonKho> TonKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatKho> XuatKhoes { get; set; }
    }
}
