//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCodeGen
    {
        public int SysCodeGenID { get; set; }
        public string TableName { get; set; }
        public string Prefix { get; set; }
        public int Length { get; set; }
        public int CurrentNumber { get; set; }
    }
}
