//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerPara
    {
        public int TimerParaID { get; set; }
        public string TimerParaCode { get; set; }
        public Nullable<decimal> TimerParaValue { get; set; }
        public string Description { get; set; }
    }
}
