//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhDoHutNuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TinhDoHutNuoc()
        {
            this.Silos = new HashSet<Silo>();
            this.TinhDoHutNuocChiTiets = new HashSet<TinhDoHutNuocChiTiet>();
        }
    
        public int TinhDoHutNuocID { get; set; }
        public string MaTinhDoHutNuoc { get; set; }
        public System.DateTime NgayTinhDoHut { get; set; }
        public int NhomSiloID { get; set; }
        public string Name { get; set; }
        public decimal DoHutNuoc { get; set; }
        public string Description { get; set; }
        public byte[] VersionNo { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
    
        public virtual NhomSilo NhomSilo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Silo> Silos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhDoHutNuocChiTiet> TinhDoHutNuocChiTiets { get; set; }
    }
}
