//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhDoHutNuocChiTiet
    {
        public int TinhDoHutNuocChiTietID { get; set; }
        public int TinhDoHutNuocID { get; set; }
        public string KichCo { get; set; }
        public decimal Percentage { get; set; }
        public decimal Value { get; set; }
        public byte[] VersionNo { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
    
        public virtual TinhDoHutNuoc TinhDoHutNuoc { get; set; }
    }
}
