//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraceRecord
    {
        public int TraceRecordID { get; set; }
        public System.DateTime RecordTime { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string FormName { get; set; }
        public string ActionName { get; set; }
        public byte[] VersionNo { get; set; }
    }
}
