//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using NDPSo.Core;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEPTramTronEntities : DbContext, IDBContext, IDisposable
    {
        public DEPTramTronEntities()
            : base("name=DEPTramTronEntities")
        {
            this.Configuration.LazyLoadingEnabled = true;
        }
        public DEPTramTronEntities(string connectionString) : base(connectionString)
        {
            this.Configuration.LazyLoadingEnabled = true;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        IDbSet<TEntity> IDBContext.Set<TEntity>()
        {
            return base.Set<TEntity>();
        }

        void IDBContext.SaveChanges()
        {
            base.SaveChanges();
        }

        public virtual DbSet<bandwidth> bandwidths { get; set; }
        public virtual DbSet<CongTruong> CongTruongs { get; set; }
        public virtual DbSet<DuLieuTron> DuLieuTrons { get; set; }
        public virtual DbSet<EventActionCode> EventActionCodes { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<MAC> MACs { get; set; }
        public virtual DbSet<MACSilo> MACSiloes { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MeTron> MeTrons { get; set; }
        public virtual DbSet<MeTronChiTiet> MeTronChiTiets { get; set; }
        public virtual DbSet<NhomSilo> NhomSiloes { get; set; }
        public virtual DbSet<PCInput> PCInputs { get; set; }
        public virtual DbSet<PCOutput> PCOutputs { get; set; }
        public virtual DbSet<PhieuTron> PhieuTrons { get; set; }
        public virtual DbSet<RptTongTungXe> RptTongTungXes { get; set; }
        public virtual DbSet<RptViewDataMix> RptViewDataMixes { get; set; }
        public virtual DbSet<SEC_Assembly> SEC_Assembly { get; set; }
        public virtual DbSet<SEC_Function> SEC_Function { get; set; }
        public virtual DbSet<SEC_Role> SEC_Role { get; set; }
        public virtual DbSet<SEC_RoleFunction> SEC_RoleFunction { get; set; }
        public virtual DbSet<SEC_TypeInfo> SEC_TypeInfo { get; set; }
        public virtual DbSet<SEC_User> SEC_User { get; set; }
        public virtual DbSet<SEC_UserRole> SEC_UserRole { get; set; }
        public virtual DbSet<Silo> Silos { get; set; }
        public virtual DbSet<SysCodeGen> SysCodeGens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiXe> TaiXes { get; set; }
        public virtual DbSet<TimerPara> TimerParas { get; set; }
        public virtual DbSet<TinhDoHutNuoc> TinhDoHutNuocs { get; set; }
        public virtual DbSet<TinhDoHutNuocChiTiet> TinhDoHutNuocChiTiets { get; set; }
        public virtual DbSet<TraceRecord> TraceRecords { get; set; }
        public virtual DbSet<VatTu> VatTus { get; set; }
        public virtual DbSet<Weigh> Weighs { get; set; }
        public virtual DbSet<WeiSiloSaving> WeiSiloSavings { get; set; }
        public virtual DbSet<WeiSiloVisible> WeiSiloVisibles { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<vw_Pivot_Ex> vw_Pivot_Ex { get; set; }
        public virtual DbSet<vw_Temp_Removing> vw_Temp_Removing { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<HangMuc> HangMucs { get; set; }
        public virtual DbSet<vw_PvSUMTotal> vw_PvSUMTotal { get; set; }
        public virtual DbSet<vw_SumWeight> vw_SumWeight { get; set; }
        public virtual DbSet<vw_PvTotalMaterial> vw_PvTotalMaterial { get; set; }
        public virtual DbSet<vw_PvMaterialDetailDay> vw_PvMaterialDetailDay { get; set; }
        public virtual DbSet<vw_PvTranferDetailDay> vw_PvTranferDetailDay { get; set; }
        public virtual DbSet<vw_PvTotalTranfer> vw_PvTotalTranfer { get; set; }
        public virtual DbSet<vw_PvTotalDriver> vw_PvTotalDriver { get; set; }
        public virtual DbSet<vw_Infos> vw_Infos { get; set; }
        public virtual DbSet<vw_InfoPT> vw_InfoPT { get; set; }
        public virtual DbSet<vw_DataMix> vw_DataMix { get; set; }
        public virtual DbSet<vw_PvtMTCT> vw_PvtMTCT { get; set; }
        public virtual DbSet<vw_PvTotalWeghit> vw_PvTotalWeghit { get; set; }
    }
}
