//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTu
    {
        public int VatTuID { get; set; }
        public string MaVatTu { get; set; }
        public string TenVatTu { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LatestUpdateDate { get; set; }
        public Nullable<int> LatestUpdatedBy { get; set; }
        public byte[] VersionNo { get; set; }
    }
}
