//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InfoPT
    {
        public int PhieuTronID { get; set; }
        public string MaPhieuTron { get; set; }
        public Nullable<System.DateTime> NgayPhieuTron { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
        public Nullable<decimal> KLDuTinh { get; set; }
        public Nullable<decimal> KLThuc { get; set; }
        public Nullable<decimal> SLMeDuTinh { get; set; }
        public Nullable<decimal> KLDuTinhCuaTungMe { get; set; }
        public int KhachHangID { get; set; }
        public string TenKhachHang { get; set; }
        public int CongTruongID { get; set; }
        public string TenCongTruong { get; set; }
        public int MACID { get; set; }
        public string TenMAC { get; set; }
        public int XeID { get; set; }
        public string BienSo { get; set; }
        public int TaiXeID { get; set; }
        public string TenTaiXe { get; set; }
        public string TenNhanVien { get; set; }
        public int NhanVienID { get; set; }
        public string TenHangMuc { get; set; }
        public int HangMucID { get; set; }
        public Nullable<bool> IsQueued { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string FullName { get; set; }
    }
}
