//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Infos
    {
        public int MeTronID { get; set; }
        public Nullable<System.DateTime> NgayMeTron { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
        public int Phieu { get; set; }
        public int PhieuTronID { get; set; }
        public string MaPhieuTron { get; set; }
        public Nullable<decimal> KLDuTinhCuaTungMe { get; set; }
        public Nullable<decimal> KLBuTruMeCuoi { get; set; }
        public int HD { get; set; }
        public string NoteHD { get; set; }
        public string MaHopDong { get; set; }
        public string KH { get; set; }
        public string NoteKH { get; set; }
        public string CT { get; set; }
        public string NoteCT { get; set; }
        public Nullable<int> TaiXeID { get; set; }
        public string Name { get; set; }
        public string TX { get; set; }
        public int TX_int { get; set; }
        public string Plate { get; set; }
        public string MAC { get; set; }
        public string NoteMAC { get; set; }
        public string DoSut { get; set; }
        public Nullable<decimal> KLVC { get; set; }
        public Nullable<decimal> KLMe { get; set; }
        public Nullable<int> NV { get; set; }
        public Nullable<int> LnNo { get; set; }
        public Nullable<int> NV_int { get; set; }
        public string TenNV { get; set; }
        public Nullable<decimal> KLDuTinh { get; set; }
        public Nullable<bool> IsQueued { get; set; }
        public string HM { get; set; }
        public Nullable<int> HM_int { get; set; }
        public Nullable<int> Xe_int { get; set; }
        public Nullable<int> MAC_int { get; set; }
        public Nullable<int> CT_int { get; set; }
        public Nullable<int> KH_int { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string FullName { get; set; }
    }
}
