//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PvtMTCT
    {
        public int MeTronID { get; set; }
        public Nullable<decimal> Agg1 { get; set; }
        public Nullable<decimal> Agg2 { get; set; }
        public Nullable<decimal> Agg3 { get; set; }
        public Nullable<decimal> Agg4 { get; set; }
        public Nullable<decimal> Agg5 { get; set; }
        public Nullable<decimal> Agg6 { get; set; }
        public Nullable<decimal> Ce1 { get; set; }
        public Nullable<decimal> Ce2 { get; set; }
        public Nullable<decimal> Ce3 { get; set; }
        public Nullable<decimal> Ce4 { get; set; }
        public Nullable<decimal> Ce5 { get; set; }
        public Nullable<decimal> Ce6 { get; set; }
        public Nullable<decimal> Wa1 { get; set; }
        public Nullable<decimal> Wa2 { get; set; }
        public Nullable<decimal> Add1 { get; set; }
        public Nullable<decimal> Add2 { get; set; }
        public Nullable<decimal> Add3 { get; set; }
        public Nullable<decimal> Add4 { get; set; }
        public Nullable<decimal> Add5 { get; set; }
        public Nullable<decimal> Add6 { get; set; }
        public Nullable<decimal> Add7 { get; set; }
        public Nullable<decimal> Add8 { get; set; }
        public Nullable<decimal> Agg1_Bat { get; set; }
        public Nullable<decimal> Agg2_Bat { get; set; }
        public Nullable<decimal> Agg3_Bat { get; set; }
        public Nullable<decimal> Agg4_Bat { get; set; }
        public Nullable<decimal> Agg5_Bat { get; set; }
        public Nullable<decimal> Agg6_Bat { get; set; }
        public Nullable<decimal> Ce1_Bat { get; set; }
        public Nullable<decimal> Ce2_Bat { get; set; }
        public Nullable<decimal> Ce3_Bat { get; set; }
        public Nullable<decimal> Ce4_Bat { get; set; }
        public Nullable<decimal> Ce5_Bat { get; set; }
        public Nullable<decimal> Ce6_Bat { get; set; }
        public Nullable<decimal> Wa1_Bat { get; set; }
        public Nullable<decimal> Wa2_Bat { get; set; }
        public Nullable<decimal> Add1_Bat { get; set; }
        public Nullable<decimal> Add2_Bat { get; set; }
        public Nullable<decimal> Add3_Bat { get; set; }
        public Nullable<decimal> Add4_Bat { get; set; }
        public Nullable<decimal> Add5_Bat { get; set; }
        public Nullable<decimal> Add6_Bat { get; set; }
        public Nullable<decimal> Add7_Bat { get; set; }
        public Nullable<decimal> Add8_Bat { get; set; }
        public Nullable<decimal> Agg1_Mac { get; set; }
        public Nullable<decimal> Agg2_Mac { get; set; }
        public Nullable<decimal> Agg3_Mac { get; set; }
        public Nullable<decimal> Agg4_Mac { get; set; }
        public Nullable<decimal> Agg5_Mac { get; set; }
        public Nullable<decimal> Agg6_Mac { get; set; }
        public Nullable<decimal> Ce1_Mac { get; set; }
        public Nullable<decimal> Ce2_Mac { get; set; }
        public Nullable<decimal> Ce3_Mac { get; set; }
        public Nullable<decimal> Ce4_Mac { get; set; }
        public Nullable<decimal> Ce5_Mac { get; set; }
        public Nullable<decimal> Ce6_Mac { get; set; }
        public Nullable<decimal> Wa1_Mac { get; set; }
        public Nullable<decimal> Wa2_Mac { get; set; }
        public Nullable<decimal> Add1_Mac { get; set; }
        public Nullable<decimal> Add2_Mac { get; set; }
        public Nullable<decimal> Add3_Mac { get; set; }
        public Nullable<decimal> Add4_Mac { get; set; }
        public Nullable<decimal> Add5_Mac { get; set; }
        public Nullable<decimal> Add6_Mac { get; set; }
        public Nullable<decimal> Add7_Mac { get; set; }
        public Nullable<decimal> Add8_Mac { get; set; }
        public Nullable<decimal> Agg1_Man { get; set; }
        public Nullable<decimal> Agg2_Man { get; set; }
        public Nullable<decimal> Agg3_Man { get; set; }
        public Nullable<decimal> Agg4_Man { get; set; }
        public Nullable<decimal> Agg5_Man { get; set; }
        public Nullable<decimal> Agg6_Man { get; set; }
        public Nullable<decimal> Ce1_Man { get; set; }
        public Nullable<decimal> Ce2_Man { get; set; }
        public Nullable<decimal> Ce3_Man { get; set; }
        public Nullable<decimal> Ce4_Man { get; set; }
        public Nullable<decimal> Ce5_Man { get; set; }
        public Nullable<decimal> Ce6_Man { get; set; }
        public Nullable<decimal> Wa1_Man { get; set; }
        public Nullable<decimal> Wa2_Man { get; set; }
        public Nullable<decimal> Add1_Man { get; set; }
        public Nullable<decimal> Add2_Man { get; set; }
        public Nullable<decimal> Add3_Man { get; set; }
        public Nullable<decimal> Add4_Man { get; set; }
        public Nullable<decimal> Add5_Man { get; set; }
        public Nullable<decimal> Add6_Man { get; set; }
        public Nullable<decimal> Add7_Man { get; set; }
        public Nullable<decimal> Add8_Man { get; set; }
        public Nullable<decimal> Agg1_Tol { get; set; }
        public Nullable<decimal> Agg2_Tol { get; set; }
        public Nullable<decimal> Agg3_Tol { get; set; }
        public Nullable<decimal> Agg4_Tol { get; set; }
        public Nullable<decimal> Agg5_Tol { get; set; }
        public Nullable<decimal> Agg6_Tol { get; set; }
        public Nullable<decimal> Ce1_Tol { get; set; }
        public Nullable<decimal> Ce2_Tol { get; set; }
        public Nullable<decimal> Ce3_Tol { get; set; }
        public Nullable<decimal> Ce4_Tol { get; set; }
        public Nullable<decimal> Ce5_Tol { get; set; }
        public Nullable<decimal> Wa1_Tol { get; set; }
        public Nullable<decimal> Wa2_Tol { get; set; }
        public Nullable<decimal> Add1_Tol { get; set; }
        public Nullable<decimal> Add2_Tol { get; set; }
        public Nullable<decimal> Add3_Tol { get; set; }
        public Nullable<decimal> Add4_Tol { get; set; }
        public Nullable<decimal> Add5_Tol { get; set; }
        public Nullable<decimal> Add6_Tol { get; set; }
        public Nullable<decimal> Add7_Tol { get; set; }
        public Nullable<decimal> Add8_Tol { get; set; }
        public Nullable<decimal> Agg1_PerTol { get; set; }
        public Nullable<decimal> Agg2_PerTol { get; set; }
        public Nullable<decimal> Agg3_PerTol { get; set; }
        public Nullable<decimal> Agg4_PerTol { get; set; }
        public Nullable<decimal> Agg5_PerTol { get; set; }
        public Nullable<decimal> Agg6_PerTol { get; set; }
        public Nullable<decimal> Ce1_PerTol { get; set; }
        public Nullable<decimal> Ce2_PerTol { get; set; }
        public Nullable<decimal> Ce3_PerTol { get; set; }
        public Nullable<decimal> Ce4_PerTol { get; set; }
        public Nullable<decimal> Ce5_PerTol { get; set; }
        public Nullable<decimal> Ce6_PerTol { get; set; }
        public Nullable<decimal> Wa1_PerTol { get; set; }
        public Nullable<decimal> Wa2_PerTol { get; set; }
        public Nullable<decimal> Add1_PerTol { get; set; }
        public Nullable<decimal> Add2_PerTol { get; set; }
        public Nullable<decimal> Add3_PerTol { get; set; }
        public Nullable<decimal> Add4_PerTol { get; set; }
        public Nullable<decimal> Add5_PerTol { get; set; }
        public Nullable<decimal> Add6_PerTol { get; set; }
        public Nullable<decimal> Add7_PerTol { get; set; }
        public Nullable<decimal> Add8_PerTol { get; set; }
    }
}
