//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PvTranferDetailDay
    {
        public int XeID { get; set; }
        public string BienSo { get; set; }
        public Nullable<int> Total_Tranfer { get; set; }
        public Nullable<decimal> Total_KL { get; set; }
        public Nullable<System.DateTime> NgayMeTron { get; set; }
        public Nullable<bool> IsQueued { get; set; }
        public string NgayMeTron_BienSo { get; set; }
    }
}
