//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PvTotalWeghit
    {
        public int PhieuTronID { get; set; }
        public Nullable<System.DateTime> NgayPhieuTron { get; set; }
        public Nullable<decimal> Total_Value_Agg1 { get; set; }
        public Nullable<decimal> Total_Value_Agg2 { get; set; }
        public Nullable<decimal> Total_Value_Agg3 { get; set; }
        public Nullable<decimal> Total_Value_Agg4 { get; set; }
        public Nullable<decimal> Total_Value_Agg5 { get; set; }
        public Nullable<decimal> Total_Value_Agg6 { get; set; }
        public Nullable<decimal> Total_Value_Ce1 { get; set; }
        public Nullable<decimal> Total_Value_Ce2 { get; set; }
        public Nullable<decimal> Total_Value_Ce3 { get; set; }
        public Nullable<decimal> Total_Value_Ce4 { get; set; }
        public Nullable<decimal> Total_Value_Ce5 { get; set; }
        public Nullable<decimal> Total_Value_Wa1 { get; set; }
        public Nullable<decimal> Total_Value_Wa2 { get; set; }
        public Nullable<decimal> Total_Value_Add1 { get; set; }
        public Nullable<decimal> Total_Value_Add2 { get; set; }
        public Nullable<decimal> Total_Value_Add3 { get; set; }
        public Nullable<decimal> Total_Value_Add4 { get; set; }
        public Nullable<decimal> Total_Value_Add5 { get; set; }
        public Nullable<decimal> Total_Value_Add6 { get; set; }
        public Nullable<decimal> Total_ValueBat_Agg1 { get; set; }
        public Nullable<decimal> Total_ValueBat_Agg2 { get; set; }
        public Nullable<decimal> Total_ValueBat_Agg3 { get; set; }
        public Nullable<decimal> Total_ValueBat_Agg4 { get; set; }
        public Nullable<decimal> Total_ValueBat_Agg5 { get; set; }
        public Nullable<decimal> Total_ValueBat_Agg6 { get; set; }
        public Nullable<decimal> Total_ValueBat_Ce1 { get; set; }
        public Nullable<decimal> Total_ValueBat_Ce2 { get; set; }
        public Nullable<decimal> Total_ValueBat_Ce3 { get; set; }
        public Nullable<decimal> Total_ValueBat_Ce4 { get; set; }
        public Nullable<decimal> Total_ValueBat_Ce5 { get; set; }
        public Nullable<decimal> Total_ValueBat_Wa1 { get; set; }
        public Nullable<decimal> Total_ValueBat_Wa2 { get; set; }
        public Nullable<decimal> Total_ValueBat_Add1 { get; set; }
        public Nullable<decimal> Total_ValueBat_Add2 { get; set; }
        public Nullable<decimal> Total_ValueBat_Add3 { get; set; }
        public Nullable<decimal> Total_ValueBat_Add4 { get; set; }
        public Nullable<decimal> Total_ValueBat_Add5 { get; set; }
        public Nullable<decimal> Total_ValueBat_Add6 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Agg1 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Agg2 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Agg3 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Agg4 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Agg5 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Agg6 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Ce1 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Ce2 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Ce3 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Ce4 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Ce5 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Wa1 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Wa2 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Add1 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Add2 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Add3 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Add4 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Add5 { get; set; }
        public Nullable<decimal> Total_ValueBatMan_Add6 { get; set; }
    }
}
