//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Pivot_Ex
    {
        public int MeTronID { get; set; }
        public Nullable<decimal> Agg1 { get; set; }
        public Nullable<decimal> Agg2 { get; set; }
        public Nullable<decimal> Agg3 { get; set; }
        public Nullable<decimal> Agg4 { get; set; }
        public Nullable<decimal> Agg5 { get; set; }
        public Nullable<decimal> Agg6 { get; set; }
        public Nullable<decimal> Ce1 { get; set; }
        public Nullable<decimal> Ce2 { get; set; }
        public Nullable<decimal> Ce3 { get; set; }
        public Nullable<decimal> Ce4 { get; set; }
        public Nullable<decimal> Wa { get; set; }
        public Nullable<decimal> Add1 { get; set; }
        public Nullable<decimal> Add2 { get; set; }
        public Nullable<decimal> Add3 { get; set; }
        public Nullable<decimal> Add4 { get; set; }
        public Nullable<decimal> Add5 { get; set; }
        public Nullable<decimal> Add6 { get; set; }
    }
}
