//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PvSUMTotal
    {
        public int PhieuTronID { get; set; }
        public Nullable<decimal> SUM_Total_Value { get; set; }
        public Nullable<decimal> SUM_Total_ValueBat { get; set; }
        public Nullable<decimal> SUM_Total_ValueBatMan { get; set; }
    }
}
