//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PvMaterialDetailDay
    {
        public int MaterialID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<decimal> Sum_ValueCP { get; set; }
        public Nullable<decimal> Sum_ValueBat { get; set; }
        public Nullable<decimal> Sum_ValueBatMan { get; set; }
        public Nullable<decimal> SaiSo { get; set; }
        public Nullable<decimal> PerSaiSo { get; set; }
        public Nullable<System.DateTime> NgayMeTron { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public Nullable<decimal> KhoiLuong { get; set; }
    }
}
