//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PvTotalDriver
    {
        public int TaiXeID { get; set; }
        public string MaTaiXe { get; set; }
        public string TenTaiXe { get; set; }
        public Nullable<int> Total_Tranfer { get; set; }
        public Nullable<decimal> Total_KL { get; set; }
        public Nullable<bool> IsManual { get; set; }
    }
}
