//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SumWeighFolPT
    {
        public int PhieuTronID { get; set; }
        public Nullable<System.DateTime> NgayPhieuTron { get; set; }
        public Nullable<decimal> TongKhoiLuong { get; set; }
        public Nullable<int> TongMeTron { get; set; }
    }
}
