//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SumWeight
    {
        public int PhieuTronID { get; set; }
        public string MaPhieuTron { get; set; }
        public Nullable<System.DateTime> NgayPhieuTron { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
        public Nullable<decimal> KLDuTinh { get; set; }
        public Nullable<decimal> KLThuc { get; set; }
        public Nullable<decimal> SLMeDuTinh { get; set; }
        public Nullable<decimal> KLDuTinhCuaTungMe { get; set; }
        public int KH_int { get; set; }
        public Nullable<int> CT_int { get; set; }
        public Nullable<int> HM_int { get; set; }
        public Nullable<int> MAC_int { get; set; }
        public Nullable<int> Xe_int { get; set; }
        public Nullable<int> TX_int { get; set; }
        public Nullable<decimal> SUM_Total_Value { get; set; }
        public Nullable<decimal> SUM_Total_ValueBat { get; set; }
        public Nullable<decimal> SUM_Total_ValueBatMan { get; set; }
        public Nullable<bool> IsQueued { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string FullName { get; set; }
        public string KH { get; set; }
        public string CT { get; set; }
        public string BS { get; set; }
        public string MAC { get; set; }
        public string TX { get; set; }
        public string HM { get; set; }
        public Nullable<decimal> TongKhoiLuong { get; set; }
        public Nullable<int> TongMeTron { get; set; }
    }
}
