//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Temp_Removing
    {
        public int MeTronChiTietID { get; set; }
        public int MeTronID { get; set; }
        public Nullable<int> MACSiloID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> ValueBat { get; set; }
        public Nullable<decimal> SiloValue { get; set; }
        public Nullable<decimal> SaiSoDuoi { get; set; }
        public Nullable<decimal> SaiSoTren { get; set; }
        public Nullable<decimal> KLCanNhoNhat { get; set; }
        public Nullable<decimal> KLCanLonNhat { get; set; }
        public Nullable<decimal> TGNhapNhaOn { get; set; }
        public Nullable<decimal> TGNhapNhaOff { get; set; }
        public Nullable<decimal> TGKiemTraVatLieuRoi { get; set; }
        public Nullable<decimal> KLRoi { get; set; }
        public Nullable<decimal> KLDT_Tu1 { get; set; }
        public Nullable<decimal> KLDT_Tu2 { get; set; }
        public Nullable<decimal> KLDT_Tu3 { get; set; }
        public Nullable<decimal> KLDT_Den1 { get; set; }
        public Nullable<decimal> KLDT_Den2 { get; set; }
        public Nullable<decimal> KLDT_Den3 { get; set; }
        public Nullable<decimal> DoAm_NhomSlioAgg { get; set; }
        public Nullable<decimal> DoHutNuoc_NhomSiloAgg { get; set; }
        public string MaSilo { get; set; }
    }
}
