//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDPSo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weigh
    {
        public int WeighID { get; set; }
        public string WeighCode { get; set; }
        public string WeighName { get; set; }
        public string Description { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<decimal> Zero { get; set; }
        public Nullable<decimal> Max { get; set; }
        public Nullable<decimal> Offset { get; set; }
        public Nullable<decimal> KLEmpty { get; set; }
        public Nullable<decimal> TimeEmpty { get; set; }
        public Nullable<decimal> Limit { get; set; }
        public Nullable<decimal> WeiToVib { get; set; }
        public Nullable<decimal> TON { get; set; }
        public Nullable<decimal> TOFF { get; set; }
        public Nullable<decimal> Spare { get; set; }
    }
}
